#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_POUND = 1,
  anon_sym_POUND_POUND = 2,
  anon_sym_POUND_POUND_POUND = 3,
  anon_sym_POUND_POUND_POUND_POUND = 4,
  anon_sym_POUND_POUND_POUND_POUND_POUND = 5,
  anon_sym_PLUS = 6,
  anon_sym_PLUS_PLUS = 7,
  anon_sym_PLUS_PLUS_PLUS = 8,
  anon_sym_PLUS_PLUS_PLUS_PLUS = 9,
  anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS = 10,
  sym_text = 11,
  sym_source_file = 12,
  sym_project = 13,
  sym_child_project = 14,
  sym_grandchild_project = 15,
  sym_great_grandchild_project = 16,
  sym_leaf_project = 17,
  sym_project_children = 18,
  sym_project_grandchildren = 19,
  sym_project_great_grandchildren = 20,
  sym_leaf_children = 21,
  sym_comment = 22,
  sym_child_comment = 23,
  sym_grandchild_comment = 24,
  sym_great_grandchild_comment = 25,
  sym_leaf_comment = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_project_repeat1 = 28,
  aux_sym_child_project_repeat1 = 29,
  aux_sym_grandchild_project_repeat1 = 30,
  aux_sym_great_grandchild_project_repeat1 = 31,
  aux_sym_leaf_project_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [anon_sym_POUND_POUND] = "##",
  [anon_sym_POUND_POUND_POUND] = "###",
  [anon_sym_POUND_POUND_POUND_POUND] = "####",
  [anon_sym_POUND_POUND_POUND_POUND_POUND] = "#####",
  [anon_sym_PLUS] = "+",
  [anon_sym_PLUS_PLUS] = "++",
  [anon_sym_PLUS_PLUS_PLUS] = "+++",
  [anon_sym_PLUS_PLUS_PLUS_PLUS] = "++++",
  [anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS] = "+++++",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [sym_project] = "project",
  [sym_child_project] = "child_project",
  [sym_grandchild_project] = "grandchild_project",
  [sym_great_grandchild_project] = "great_grandchild_project",
  [sym_leaf_project] = "leaf_project",
  [sym_project_children] = "project_children",
  [sym_project_grandchildren] = "project_grandchildren",
  [sym_project_great_grandchildren] = "project_great_grandchildren",
  [sym_leaf_children] = "leaf_children",
  [sym_comment] = "comment",
  [sym_child_comment] = "child_comment",
  [sym_grandchild_comment] = "grandchild_comment",
  [sym_great_grandchild_comment] = "great_grandchild_comment",
  [sym_leaf_comment] = "leaf_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_project_repeat1] = "project_repeat1",
  [aux_sym_child_project_repeat1] = "child_project_repeat1",
  [aux_sym_grandchild_project_repeat1] = "grandchild_project_repeat1",
  [aux_sym_great_grandchild_project_repeat1] = "great_grandchild_project_repeat1",
  [aux_sym_leaf_project_repeat1] = "leaf_project_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_POUND_POUND] = anon_sym_POUND_POUND,
  [anon_sym_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND,
  [anon_sym_POUND_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND_POUND,
  [anon_sym_POUND_POUND_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND_POUND_POUND,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_PLUS_PLUS] = anon_sym_PLUS_PLUS,
  [anon_sym_PLUS_PLUS_PLUS] = anon_sym_PLUS_PLUS_PLUS,
  [anon_sym_PLUS_PLUS_PLUS_PLUS] = anon_sym_PLUS_PLUS_PLUS_PLUS,
  [anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS] = anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [sym_project] = sym_project,
  [sym_child_project] = sym_child_project,
  [sym_grandchild_project] = sym_grandchild_project,
  [sym_great_grandchild_project] = sym_great_grandchild_project,
  [sym_leaf_project] = sym_leaf_project,
  [sym_project_children] = sym_project_children,
  [sym_project_grandchildren] = sym_project_grandchildren,
  [sym_project_great_grandchildren] = sym_project_great_grandchildren,
  [sym_leaf_children] = sym_leaf_children,
  [sym_comment] = sym_comment,
  [sym_child_comment] = sym_child_comment,
  [sym_grandchild_comment] = sym_grandchild_comment,
  [sym_great_grandchild_comment] = sym_great_grandchild_comment,
  [sym_leaf_comment] = sym_leaf_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_project_repeat1] = aux_sym_project_repeat1,
  [aux_sym_child_project_repeat1] = aux_sym_child_project_repeat1,
  [aux_sym_grandchild_project_repeat1] = aux_sym_grandchild_project_repeat1,
  [aux_sym_great_grandchild_project_repeat1] = aux_sym_great_grandchild_project_repeat1,
  [aux_sym_leaf_project_repeat1] = aux_sym_leaf_project_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_project] = {
    .visible = true,
    .named = true,
  },
  [sym_child_project] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_project] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_project] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_project] = {
    .visible = true,
    .named = true,
  },
  [sym_project_children] = {
    .visible = true,
    .named = true,
  },
  [sym_project_grandchildren] = {
    .visible = true,
    .named = true,
  },
  [sym_project_great_grandchildren] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_children] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_child_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_child_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_grandchild_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_great_grandchild_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_leaf_project_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == '+') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(4);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      if (lookahead == '#') ADVANCE(5);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      if (lookahead == '#') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND_POUND);
      if (lookahead == '#') ADVANCE(7);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND_POUND_POUND);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '+') ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS);
      if (lookahead == '+') ADVANCE(10);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS_PLUS);
      if (lookahead == '+') ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS_PLUS_PLUS);
      if (lookahead == '+') ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(38),
    [sym_project] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    ACTIONS(13), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    STATE(4), 2,
      sym_leaf_children,
      aux_sym_great_grandchild_project_repeat1,
    STATE(15), 2,
      sym_leaf_project,
      sym_great_grandchild_comment,
    ACTIONS(9), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
  [27] = 6,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    ACTIONS(22), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    STATE(3), 2,
      sym_leaf_children,
      aux_sym_great_grandchild_project_repeat1,
    STATE(15), 2,
      sym_leaf_project,
      sym_great_grandchild_comment,
    ACTIONS(17), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
  [54] = 6,
    ACTIONS(11), 1,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    ACTIONS(13), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_leaf_children,
      aux_sym_great_grandchild_project_repeat1,
    STATE(15), 2,
      sym_leaf_project,
      sym_great_grandchild_comment,
    ACTIONS(27), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
  [81] = 4,
    ACTIONS(33), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    STATE(5), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(31), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
  [103] = 4,
    ACTIONS(40), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(36), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    STATE(5), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(38), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
  [125] = 4,
    ACTIONS(40), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    STATE(6), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(44), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
  [147] = 6,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(53), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(8), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(17), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(48), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
  [172] = 6,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(62), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(8), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(17), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(58), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
  [197] = 6,
    ACTIONS(60), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(62), 1,
      anon_sym_PLUS_PLUS_PLUS,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    STATE(9), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(17), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(66), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
  [222] = 2,
    ACTIONS(68), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(70), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
  [238] = 6,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(78), 1,
      anon_sym_PLUS_PLUS,
    STATE(16), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(22), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(74), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [261] = 6,
    ACTIONS(76), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(78), 1,
      anon_sym_PLUS_PLUS,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    STATE(12), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(22), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(82), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [284] = 2,
    ACTIONS(84), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(86), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
  [299] = 2,
    ACTIONS(88), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(90), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
  [314] = 6,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(99), 1,
      anon_sym_PLUS_PLUS,
    STATE(16), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(22), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(94), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [337] = 2,
    ACTIONS(102), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS,
    ACTIONS(104), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
  [350] = 6,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    ACTIONS(108), 1,
      anon_sym_POUND,
    ACTIONS(110), 1,
      anon_sym_POUND_POUND,
    ACTIONS(112), 1,
      anon_sym_PLUS,
    STATE(20), 2,
      sym_project_children,
      aux_sym_project_repeat1,
    STATE(24), 2,
      sym_child_project,
      sym_comment,
  [371] = 6,
    ACTIONS(110), 1,
      anon_sym_POUND_POUND,
    ACTIONS(112), 1,
      anon_sym_PLUS,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 1,
      anon_sym_POUND,
    STATE(18), 2,
      sym_project_children,
      aux_sym_project_repeat1,
    STATE(24), 2,
      sym_child_project,
      sym_comment,
  [392] = 6,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 1,
      anon_sym_POUND,
    ACTIONS(122), 1,
      anon_sym_POUND_POUND,
    ACTIONS(125), 1,
      anon_sym_PLUS,
    STATE(20), 2,
      sym_project_children,
      aux_sym_project_repeat1,
    STATE(24), 2,
      sym_child_project,
      sym_comment,
  [413] = 2,
    ACTIONS(128), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS,
    ACTIONS(130), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
  [426] = 2,
    ACTIONS(132), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS,
    ACTIONS(134), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [437] = 2,
    ACTIONS(136), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS,
    ACTIONS(138), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [448] = 2,
    ACTIONS(142), 1,
      anon_sym_POUND,
    ACTIONS(140), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [457] = 3,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
    ACTIONS(146), 1,
      anon_sym_POUND,
    STATE(25), 2,
      sym_project,
      aux_sym_source_file_repeat1,
  [468] = 3,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    STATE(25), 2,
      sym_project,
      aux_sym_source_file_repeat1,
  [479] = 2,
    ACTIONS(153), 1,
      anon_sym_POUND,
    ACTIONS(151), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [488] = 1,
    ACTIONS(155), 1,
      sym_text,
  [492] = 1,
    ACTIONS(157), 1,
      sym_text,
  [496] = 1,
    ACTIONS(159), 1,
      sym_text,
  [500] = 1,
    ACTIONS(161), 1,
      sym_text,
  [504] = 1,
    ACTIONS(163), 1,
      sym_text,
  [508] = 1,
    ACTIONS(165), 1,
      sym_text,
  [512] = 1,
    ACTIONS(167), 1,
      sym_text,
  [516] = 1,
    ACTIONS(169), 1,
      sym_text,
  [520] = 1,
    ACTIONS(171), 1,
      sym_text,
  [524] = 1,
    ACTIONS(173), 1,
      sym_text,
  [528] = 1,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 81,
  [SMALL_STATE(6)] = 103,
  [SMALL_STATE(7)] = 125,
  [SMALL_STATE(8)] = 147,
  [SMALL_STATE(9)] = 172,
  [SMALL_STATE(10)] = 197,
  [SMALL_STATE(11)] = 222,
  [SMALL_STATE(12)] = 238,
  [SMALL_STATE(13)] = 261,
  [SMALL_STATE(14)] = 284,
  [SMALL_STATE(15)] = 299,
  [SMALL_STATE(16)] = 314,
  [SMALL_STATE(17)] = 337,
  [SMALL_STATE(18)] = 350,
  [SMALL_STATE(19)] = 371,
  [SMALL_STATE(20)] = 392,
  [SMALL_STATE(21)] = 413,
  [SMALL_STATE(22)] = 426,
  [SMALL_STATE(23)] = 437,
  [SMALL_STATE(24)] = 448,
  [SMALL_STATE(25)] = 457,
  [SMALL_STATE(26)] = 468,
  [SMALL_STATE(27)] = 479,
  [SMALL_STATE(28)] = 488,
  [SMALL_STATE(29)] = 492,
  [SMALL_STATE(30)] = 496,
  [SMALL_STATE(31)] = 500,
  [SMALL_STATE(32)] = 504,
  [SMALL_STATE(33)] = 508,
  [SMALL_STATE(34)] = 512,
  [SMALL_STATE(35)] = 516,
  [SMALL_STATE(36)] = 520,
  [SMALL_STATE(37)] = 524,
  [SMALL_STATE(38)] = 528,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 2),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2), SHIFT_REPEAT(31),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2), SHIFT_REPEAT(32),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 3),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_leaf_project_repeat1, 2),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_leaf_project_repeat1, 2),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_leaf_project_repeat1, 2), SHIFT_REPEAT(37),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 3),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 3),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 2),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 2),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_grandchild_project_repeat1, 2),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2), SHIFT_REPEAT(35),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2), SHIFT_REPEAT(36),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 3),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 3),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 2),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 2),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_comment, 2),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_comment, 2),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 3),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 3),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 2),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 2),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_comment, 2),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_comment, 2),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_children, 1),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_children, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_child_project_repeat1, 2),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2), SHIFT_REPEAT(33),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2), SHIFT_REPEAT(28),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project_great_grandchildren, 1),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project_great_grandchildren, 1),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project, 3),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project, 2),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project, 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_project_repeat1, 2),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_project_repeat1, 2),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_project_repeat1, 2), SHIFT_REPEAT(34),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_project_repeat1, 2), SHIFT_REPEAT(30),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_comment, 2),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_comment, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project_grandchildren, 1),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project_grandchildren, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_comment, 2),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_comment, 2),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project_children, 1),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project_children, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(29),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [175] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_projects(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
