#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_POUND = 1,
  anon_sym_POUND_POUND = 2,
  anon_sym_POUND_POUND_POUND = 3,
  anon_sym_POUND_POUND_POUND_POUND = 4,
  anon_sym_POUND_POUND_POUND_POUND_POUND = 5,
  anon_sym_PLUS = 6,
  anon_sym_PLUS_PLUS = 7,
  anon_sym_PLUS_PLUS_PLUS = 8,
  anon_sym_PLUS_PLUS_PLUS_PLUS = 9,
  anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS = 10,
  sym_text = 11,
  sym_root_collapsed = 12,
  sym_root_not_collapsed = 13,
  sym_child_collapsed = 14,
  sym_child_not_collapsed = 15,
  sym_grandchild_collapsed = 16,
  sym_grandchild_not_collapsed = 17,
  sym_great_grandchild_collapsed = 18,
  sym_great_grandchild_not_collapsed = 19,
  sym_leaf_collapsed = 20,
  sym_leaf_not_collapsed = 21,
  sym_source_file = 22,
  sym_root_project = 23,
  sym_child_project = 24,
  sym_grandchild_project = 25,
  sym_great_grandchild_project = 26,
  sym_leaf_project = 27,
  sym_project_children = 28,
  sym_project_grandchildren = 29,
  sym_project_great_grandchildren = 30,
  sym_leaf_children = 31,
  sym_root_comment = 32,
  sym_child_comment = 33,
  sym_grandchild_comment = 34,
  sym_great_grandchild_comment = 35,
  sym_leaf_comment = 36,
  sym_root_collapsed_icon = 37,
  sym_child_collapsed_icon = 38,
  sym_grandchild_collapsed_icon = 39,
  sym_great_grandchild_collapsed_icon = 40,
  sym_leaf_collapsed_icon = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_root_project_repeat1 = 43,
  aux_sym_child_project_repeat1 = 44,
  aux_sym_grandchild_project_repeat1 = 45,
  aux_sym_great_grandchild_project_repeat1 = 46,
  aux_sym_leaf_project_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [anon_sym_POUND_POUND] = "##",
  [anon_sym_POUND_POUND_POUND] = "###",
  [anon_sym_POUND_POUND_POUND_POUND] = "####",
  [anon_sym_POUND_POUND_POUND_POUND_POUND] = "#####",
  [anon_sym_PLUS] = "+",
  [anon_sym_PLUS_PLUS] = "++",
  [anon_sym_PLUS_PLUS_PLUS] = "+++",
  [anon_sym_PLUS_PLUS_PLUS_PLUS] = "++++",
  [anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS] = "+++++",
  [sym_text] = "text",
  [sym_root_collapsed] = "root_collapsed",
  [sym_root_not_collapsed] = "root_not_collapsed",
  [sym_child_collapsed] = "child_collapsed",
  [sym_child_not_collapsed] = "child_not_collapsed",
  [sym_grandchild_collapsed] = "grandchild_collapsed",
  [sym_grandchild_not_collapsed] = "grandchild_not_collapsed",
  [sym_great_grandchild_collapsed] = "great_grandchild_collapsed",
  [sym_great_grandchild_not_collapsed] = "great_grandchild_not_collapsed",
  [sym_leaf_collapsed] = "leaf_collapsed",
  [sym_leaf_not_collapsed] = "leaf_not_collapsed",
  [sym_source_file] = "source_file",
  [sym_root_project] = "root_project",
  [sym_child_project] = "child_project",
  [sym_grandchild_project] = "grandchild_project",
  [sym_great_grandchild_project] = "great_grandchild_project",
  [sym_leaf_project] = "leaf_project",
  [sym_project_children] = "project_children",
  [sym_project_grandchildren] = "project_grandchildren",
  [sym_project_great_grandchildren] = "project_great_grandchildren",
  [sym_leaf_children] = "leaf_children",
  [sym_root_comment] = "root_comment",
  [sym_child_comment] = "child_comment",
  [sym_grandchild_comment] = "grandchild_comment",
  [sym_great_grandchild_comment] = "great_grandchild_comment",
  [sym_leaf_comment] = "leaf_comment",
  [sym_root_collapsed_icon] = "root_collapsed_icon",
  [sym_child_collapsed_icon] = "child_collapsed_icon",
  [sym_grandchild_collapsed_icon] = "grandchild_collapsed_icon",
  [sym_great_grandchild_collapsed_icon] = "great_grandchild_collapsed_icon",
  [sym_leaf_collapsed_icon] = "leaf_collapsed_icon",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_root_project_repeat1] = "root_project_repeat1",
  [aux_sym_child_project_repeat1] = "child_project_repeat1",
  [aux_sym_grandchild_project_repeat1] = "grandchild_project_repeat1",
  [aux_sym_great_grandchild_project_repeat1] = "great_grandchild_project_repeat1",
  [aux_sym_leaf_project_repeat1] = "leaf_project_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_POUND_POUND] = anon_sym_POUND_POUND,
  [anon_sym_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND,
  [anon_sym_POUND_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND_POUND,
  [anon_sym_POUND_POUND_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND_POUND_POUND,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_PLUS_PLUS] = anon_sym_PLUS_PLUS,
  [anon_sym_PLUS_PLUS_PLUS] = anon_sym_PLUS_PLUS_PLUS,
  [anon_sym_PLUS_PLUS_PLUS_PLUS] = anon_sym_PLUS_PLUS_PLUS_PLUS,
  [anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS] = anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
  [sym_text] = sym_text,
  [sym_root_collapsed] = sym_root_collapsed,
  [sym_root_not_collapsed] = sym_root_not_collapsed,
  [sym_child_collapsed] = sym_child_collapsed,
  [sym_child_not_collapsed] = sym_child_not_collapsed,
  [sym_grandchild_collapsed] = sym_grandchild_collapsed,
  [sym_grandchild_not_collapsed] = sym_grandchild_not_collapsed,
  [sym_great_grandchild_collapsed] = sym_great_grandchild_collapsed,
  [sym_great_grandchild_not_collapsed] = sym_great_grandchild_not_collapsed,
  [sym_leaf_collapsed] = sym_leaf_collapsed,
  [sym_leaf_not_collapsed] = sym_leaf_not_collapsed,
  [sym_source_file] = sym_source_file,
  [sym_root_project] = sym_root_project,
  [sym_child_project] = sym_child_project,
  [sym_grandchild_project] = sym_grandchild_project,
  [sym_great_grandchild_project] = sym_great_grandchild_project,
  [sym_leaf_project] = sym_leaf_project,
  [sym_project_children] = sym_project_children,
  [sym_project_grandchildren] = sym_project_grandchildren,
  [sym_project_great_grandchildren] = sym_project_great_grandchildren,
  [sym_leaf_children] = sym_leaf_children,
  [sym_root_comment] = sym_root_comment,
  [sym_child_comment] = sym_child_comment,
  [sym_grandchild_comment] = sym_grandchild_comment,
  [sym_great_grandchild_comment] = sym_great_grandchild_comment,
  [sym_leaf_comment] = sym_leaf_comment,
  [sym_root_collapsed_icon] = sym_root_collapsed_icon,
  [sym_child_collapsed_icon] = sym_child_collapsed_icon,
  [sym_grandchild_collapsed_icon] = sym_grandchild_collapsed_icon,
  [sym_great_grandchild_collapsed_icon] = sym_great_grandchild_collapsed_icon,
  [sym_leaf_collapsed_icon] = sym_leaf_collapsed_icon,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_root_project_repeat1] = aux_sym_root_project_repeat1,
  [aux_sym_child_project_repeat1] = aux_sym_child_project_repeat1,
  [aux_sym_grandchild_project_repeat1] = aux_sym_grandchild_project_repeat1,
  [aux_sym_great_grandchild_project_repeat1] = aux_sym_great_grandchild_project_repeat1,
  [aux_sym_leaf_project_repeat1] = aux_sym_leaf_project_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_root_collapsed] = {
    .visible = true,
    .named = true,
  },
  [sym_root_not_collapsed] = {
    .visible = true,
    .named = true,
  },
  [sym_child_collapsed] = {
    .visible = true,
    .named = true,
  },
  [sym_child_not_collapsed] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_collapsed] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_not_collapsed] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_collapsed] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_not_collapsed] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_collapsed] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_not_collapsed] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_root_project] = {
    .visible = true,
    .named = true,
  },
  [sym_child_project] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_project] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_project] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_project] = {
    .visible = true,
    .named = true,
  },
  [sym_project_children] = {
    .visible = true,
    .named = true,
  },
  [sym_project_grandchildren] = {
    .visible = true,
    .named = true,
  },
  [sym_project_great_grandchildren] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_children] = {
    .visible = true,
    .named = true,
  },
  [sym_root_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_child_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_root_collapsed_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_child_collapsed_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_collapsed_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_collapsed_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_collapsed_icon] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_child_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_grandchild_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_great_grandchild_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_leaf_project_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '+') ADVANCE(18);
      if (lookahead == '>') ADVANCE(1);
      if (lookahead == 'v') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(25);
      if (lookahead == '>') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead == 'v') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead == '>') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(28);
      if (lookahead == 'v') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(29);
      if (lookahead == '>') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(30);
      if (lookahead == 'v') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(31);
      if (lookahead == '>') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(32);
      if (lookahead == 'v') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') SKIP(11)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      if (lookahead == '#') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      if (lookahead == '#') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND_POUND);
      if (lookahead == '#') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND_POUND_POUND);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '+') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS);
      if (lookahead == '+') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS_PLUS);
      if (lookahead == '+') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS_PLUS_PLUS);
      if (lookahead == '+') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_root_collapsed);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_root_not_collapsed);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_child_collapsed);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_child_not_collapsed);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_grandchild_collapsed);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_grandchild_not_collapsed);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_great_grandchild_collapsed);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_great_grandchild_not_collapsed);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_leaf_collapsed);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_leaf_not_collapsed);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 11},
  [39] = {.lex_state = 11},
  [40] = {.lex_state = 11},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 11},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 11},
  [54] = {.lex_state = 11},
  [55] = {.lex_state = 11},
  [56] = {.lex_state = 11},
  [57] = {.lex_state = 11},
  [58] = {.lex_state = 11},
  [59] = {.lex_state = 11},
  [60] = {.lex_state = 11},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS] = ACTIONS(1),
    [sym_root_collapsed] = ACTIONS(1),
    [sym_root_not_collapsed] = ACTIONS(1),
    [sym_child_collapsed] = ACTIONS(1),
    [sym_child_not_collapsed] = ACTIONS(1),
    [sym_grandchild_collapsed] = ACTIONS(1),
    [sym_grandchild_not_collapsed] = ACTIONS(1),
    [sym_great_grandchild_collapsed] = ACTIONS(1),
    [sym_great_grandchild_not_collapsed] = ACTIONS(1),
    [sym_leaf_collapsed] = ACTIONS(1),
    [sym_leaf_not_collapsed] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(62),
    [sym_root_project] = STATE(36),
    [sym_root_collapsed_icon] = STATE(61),
    [aux_sym_source_file_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
    [sym_root_collapsed] = ACTIONS(7),
    [sym_root_not_collapsed] = ACTIONS(7),
  },
  [2] = {
    [sym_leaf_project] = STATE(19),
    [sym_leaf_children] = STATE(6),
    [sym_great_grandchild_comment] = STATE(19),
    [sym_leaf_collapsed_icon] = STATE(50),
    [aux_sym_great_grandchild_project_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_POUND_POUND] = ACTIONS(11),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(11),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(11),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_PLUS_PLUS] = ACTIONS(11),
    [anon_sym_PLUS_PLUS_PLUS] = ACTIONS(11),
    [anon_sym_PLUS_PLUS_PLUS_PLUS] = ACTIONS(15),
    [sym_root_collapsed] = ACTIONS(9),
    [sym_root_not_collapsed] = ACTIONS(9),
    [sym_child_collapsed] = ACTIONS(9),
    [sym_child_not_collapsed] = ACTIONS(9),
    [sym_grandchild_collapsed] = ACTIONS(9),
    [sym_grandchild_not_collapsed] = ACTIONS(9),
    [sym_great_grandchild_collapsed] = ACTIONS(9),
    [sym_great_grandchild_not_collapsed] = ACTIONS(9),
    [sym_leaf_collapsed] = ACTIONS(17),
    [sym_leaf_not_collapsed] = ACTIONS(17),
  },
  [3] = {
    [sym_leaf_project] = STATE(19),
    [sym_leaf_children] = STATE(4),
    [sym_great_grandchild_comment] = STATE(19),
    [sym_leaf_collapsed_icon] = STATE(50),
    [aux_sym_great_grandchild_project_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_POUND] = ACTIONS(21),
    [anon_sym_POUND_POUND] = ACTIONS(21),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(21),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(21),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_PLUS_PLUS] = ACTIONS(21),
    [anon_sym_PLUS_PLUS_PLUS] = ACTIONS(21),
    [anon_sym_PLUS_PLUS_PLUS_PLUS] = ACTIONS(15),
    [sym_root_collapsed] = ACTIONS(19),
    [sym_root_not_collapsed] = ACTIONS(19),
    [sym_child_collapsed] = ACTIONS(19),
    [sym_child_not_collapsed] = ACTIONS(19),
    [sym_grandchild_collapsed] = ACTIONS(19),
    [sym_grandchild_not_collapsed] = ACTIONS(19),
    [sym_great_grandchild_collapsed] = ACTIONS(19),
    [sym_great_grandchild_not_collapsed] = ACTIONS(19),
    [sym_leaf_collapsed] = ACTIONS(17),
    [sym_leaf_not_collapsed] = ACTIONS(17),
  },
  [4] = {
    [sym_leaf_project] = STATE(19),
    [sym_leaf_children] = STATE(6),
    [sym_great_grandchild_comment] = STATE(19),
    [sym_leaf_collapsed_icon] = STATE(50),
    [aux_sym_great_grandchild_project_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_POUND_POUND] = ACTIONS(25),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(25),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(25),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_PLUS_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_PLUS_PLUS_PLUS_PLUS] = ACTIONS(15),
    [sym_root_collapsed] = ACTIONS(23),
    [sym_root_not_collapsed] = ACTIONS(23),
    [sym_child_collapsed] = ACTIONS(23),
    [sym_child_not_collapsed] = ACTIONS(23),
    [sym_grandchild_collapsed] = ACTIONS(23),
    [sym_grandchild_not_collapsed] = ACTIONS(23),
    [sym_great_grandchild_collapsed] = ACTIONS(23),
    [sym_great_grandchild_not_collapsed] = ACTIONS(23),
    [sym_leaf_collapsed] = ACTIONS(17),
    [sym_leaf_not_collapsed] = ACTIONS(17),
  },
  [5] = {
    [sym_leaf_project] = STATE(19),
    [sym_leaf_children] = STATE(2),
    [sym_great_grandchild_comment] = STATE(19),
    [sym_leaf_collapsed_icon] = STATE(50),
    [aux_sym_great_grandchild_project_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_POUND_POUND] = ACTIONS(25),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(25),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(25),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_PLUS_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_PLUS_PLUS_PLUS_PLUS] = ACTIONS(15),
    [sym_root_collapsed] = ACTIONS(23),
    [sym_root_not_collapsed] = ACTIONS(23),
    [sym_child_collapsed] = ACTIONS(23),
    [sym_child_not_collapsed] = ACTIONS(23),
    [sym_grandchild_collapsed] = ACTIONS(23),
    [sym_grandchild_not_collapsed] = ACTIONS(23),
    [sym_great_grandchild_collapsed] = ACTIONS(23),
    [sym_great_grandchild_not_collapsed] = ACTIONS(23),
    [sym_leaf_collapsed] = ACTIONS(17),
    [sym_leaf_not_collapsed] = ACTIONS(17),
  },
  [6] = {
    [sym_leaf_project] = STATE(19),
    [sym_leaf_children] = STATE(6),
    [sym_great_grandchild_comment] = STATE(19),
    [sym_leaf_collapsed_icon] = STATE(50),
    [aux_sym_great_grandchild_project_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(29),
    [anon_sym_POUND_POUND] = ACTIONS(29),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(29),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(29),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_PLUS_PLUS] = ACTIONS(29),
    [anon_sym_PLUS_PLUS_PLUS] = ACTIONS(29),
    [anon_sym_PLUS_PLUS_PLUS_PLUS] = ACTIONS(34),
    [sym_root_collapsed] = ACTIONS(27),
    [sym_root_not_collapsed] = ACTIONS(27),
    [sym_child_collapsed] = ACTIONS(27),
    [sym_child_not_collapsed] = ACTIONS(27),
    [sym_grandchild_collapsed] = ACTIONS(27),
    [sym_grandchild_not_collapsed] = ACTIONS(27),
    [sym_great_grandchild_collapsed] = ACTIONS(27),
    [sym_great_grandchild_not_collapsed] = ACTIONS(27),
    [sym_leaf_collapsed] = ACTIONS(37),
    [sym_leaf_not_collapsed] = ACTIONS(37),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(44), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    STATE(11), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(42), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(40), 12,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
      sym_leaf_collapsed,
      sym_leaf_not_collapsed,
  [32] = 4,
    ACTIONS(44), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    STATE(7), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(48), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(46), 12,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
      sym_leaf_collapsed,
      sym_leaf_not_collapsed,
  [64] = 4,
    ACTIONS(44), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    STATE(11), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(52), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(50), 12,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
      sym_leaf_collapsed,
      sym_leaf_not_collapsed,
  [96] = 4,
    ACTIONS(44), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    STATE(9), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(42), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(40), 12,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
      sym_leaf_collapsed,
      sym_leaf_not_collapsed,
  [128] = 4,
    ACTIONS(58), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    STATE(11), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(56), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(54), 12,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
      sym_leaf_collapsed,
      sym_leaf_not_collapsed,
  [160] = 8,
    ACTIONS(65), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(67), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(41), 1,
      sym_great_grandchild_collapsed_icon,
    ACTIONS(69), 2,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
    STATE(14), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(26), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(63), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
    ACTIONS(61), 7,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
  [198] = 2,
    ACTIONS(73), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(71), 13,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
      sym_leaf_collapsed,
      sym_leaf_not_collapsed,
  [224] = 8,
    ACTIONS(79), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(82), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(41), 1,
      sym_great_grandchild_collapsed_icon,
    ACTIONS(85), 2,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
    STATE(14), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(26), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(77), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
  [262] = 8,
    ACTIONS(65), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(67), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(41), 1,
      sym_great_grandchild_collapsed_icon,
    ACTIONS(69), 2,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
    STATE(12), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(26), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(90), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
    ACTIONS(88), 7,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
  [300] = 8,
    ACTIONS(65), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(67), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(41), 1,
      sym_great_grandchild_collapsed_icon,
    ACTIONS(69), 2,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
    STATE(14), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(26), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(90), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
    ACTIONS(88), 7,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
  [338] = 8,
    ACTIONS(65), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(67), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(41), 1,
      sym_great_grandchild_collapsed_icon,
    ACTIONS(69), 2,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
    STATE(16), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(26), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(94), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
    ACTIONS(92), 7,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
  [376] = 2,
    ACTIONS(98), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
    ACTIONS(96), 13,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
      sym_leaf_collapsed,
      sym_leaf_not_collapsed,
  [401] = 2,
    ACTIONS(102), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
    ACTIONS(100), 13,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
      sym_leaf_collapsed,
      sym_leaf_not_collapsed,
  [426] = 8,
    ACTIONS(108), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(110), 1,
      anon_sym_PLUS_PLUS,
    STATE(45), 1,
      sym_grandchild_collapsed_icon,
    ACTIONS(112), 2,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
    STATE(24), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(32), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(106), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
    ACTIONS(104), 5,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
  [460] = 8,
    ACTIONS(108), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(110), 1,
      anon_sym_PLUS_PLUS,
    STATE(45), 1,
      sym_grandchild_collapsed_icon,
    ACTIONS(112), 2,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
    STATE(20), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(32), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(116), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
    ACTIONS(114), 5,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
  [494] = 8,
    ACTIONS(108), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(110), 1,
      anon_sym_PLUS_PLUS,
    STATE(45), 1,
      sym_grandchild_collapsed_icon,
    ACTIONS(112), 2,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
    STATE(24), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(32), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(120), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
    ACTIONS(118), 5,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
  [528] = 8,
    ACTIONS(108), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(110), 1,
      anon_sym_PLUS_PLUS,
    STATE(45), 1,
      sym_grandchild_collapsed_icon,
    ACTIONS(112), 2,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
    STATE(22), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(32), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(106), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
    ACTIONS(104), 5,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
  [562] = 8,
    ACTIONS(126), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(129), 1,
      anon_sym_PLUS_PLUS,
    STATE(45), 1,
      sym_grandchild_collapsed_icon,
    ACTIONS(132), 2,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
    STATE(24), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(32), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(124), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
    ACTIONS(122), 5,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
  [596] = 2,
    ACTIONS(137), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
    ACTIONS(135), 11,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
  [617] = 2,
    ACTIONS(141), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
    ACTIONS(139), 11,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
      sym_great_grandchild_collapsed,
      sym_great_grandchild_not_collapsed,
  [638] = 8,
    ACTIONS(145), 1,
      anon_sym_POUND,
    ACTIONS(147), 1,
      anon_sym_POUND_POUND,
    ACTIONS(149), 1,
      anon_sym_PLUS,
    STATE(49), 1,
      sym_child_collapsed_icon,
    ACTIONS(151), 2,
      sym_child_collapsed,
      sym_child_not_collapsed,
    STATE(28), 2,
      sym_project_children,
      aux_sym_root_project_repeat1,
    STATE(34), 2,
      sym_child_project,
      sym_root_comment,
    ACTIONS(143), 3,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
  [668] = 8,
    ACTIONS(155), 1,
      anon_sym_POUND,
    ACTIONS(157), 1,
      anon_sym_POUND_POUND,
    ACTIONS(160), 1,
      anon_sym_PLUS,
    STATE(49), 1,
      sym_child_collapsed_icon,
    ACTIONS(163), 2,
      sym_child_collapsed,
      sym_child_not_collapsed,
    STATE(28), 2,
      sym_project_children,
      aux_sym_root_project_repeat1,
    STATE(34), 2,
      sym_child_project,
      sym_root_comment,
    ACTIONS(153), 3,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
  [698] = 8,
    ACTIONS(147), 1,
      anon_sym_POUND_POUND,
    ACTIONS(149), 1,
      anon_sym_PLUS,
    ACTIONS(168), 1,
      anon_sym_POUND,
    STATE(49), 1,
      sym_child_collapsed_icon,
    ACTIONS(151), 2,
      sym_child_collapsed,
      sym_child_not_collapsed,
    STATE(27), 2,
      sym_project_children,
      aux_sym_root_project_repeat1,
    STATE(34), 2,
      sym_child_project,
      sym_root_comment,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
  [728] = 8,
    ACTIONS(145), 1,
      anon_sym_POUND,
    ACTIONS(147), 1,
      anon_sym_POUND_POUND,
    ACTIONS(149), 1,
      anon_sym_PLUS,
    STATE(49), 1,
      sym_child_collapsed_icon,
    ACTIONS(151), 2,
      sym_child_collapsed,
      sym_child_not_collapsed,
    STATE(31), 2,
      sym_project_children,
      aux_sym_root_project_repeat1,
    STATE(34), 2,
      sym_child_project,
      sym_root_comment,
    ACTIONS(143), 3,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
  [758] = 8,
    ACTIONS(147), 1,
      anon_sym_POUND_POUND,
    ACTIONS(149), 1,
      anon_sym_PLUS,
    ACTIONS(172), 1,
      anon_sym_POUND,
    STATE(49), 1,
      sym_child_collapsed_icon,
    ACTIONS(151), 2,
      sym_child_collapsed,
      sym_child_not_collapsed,
    STATE(28), 2,
      sym_project_children,
      aux_sym_root_project_repeat1,
    STATE(34), 2,
      sym_child_project,
      sym_root_comment,
    ACTIONS(170), 3,
      ts_builtin_sym_end,
      sym_root_collapsed,
      sym_root_not_collapsed,
  [788] = 2,
    ACTIONS(176), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
    ACTIONS(174), 9,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
  [805] = 2,
    ACTIONS(180), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
    ACTIONS(178), 9,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
      sym_grandchild_collapsed,
      sym_grandchild_not_collapsed,
  [822] = 2,
    ACTIONS(184), 1,
      anon_sym_POUND,
    ACTIONS(182), 7,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
  [835] = 2,
    ACTIONS(188), 1,
      anon_sym_POUND,
    ACTIONS(186), 7,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
      sym_root_collapsed,
      sym_root_not_collapsed,
      sym_child_collapsed,
      sym_child_not_collapsed,
  [848] = 5,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(190), 1,
      ts_builtin_sym_end,
    STATE(61), 1,
      sym_root_collapsed_icon,
    ACTIONS(7), 2,
      sym_root_collapsed,
      sym_root_not_collapsed,
    STATE(37), 2,
      sym_root_project,
      aux_sym_source_file_repeat1,
  [866] = 5,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
    ACTIONS(194), 1,
      anon_sym_POUND,
    STATE(61), 1,
      sym_root_collapsed_icon,
    ACTIONS(197), 2,
      sym_root_collapsed,
      sym_root_not_collapsed,
    STATE(37), 2,
      sym_root_project,
      aux_sym_source_file_repeat1,
  [884] = 1,
    ACTIONS(200), 1,
      sym_text,
  [888] = 1,
    ACTIONS(202), 1,
      sym_text,
  [892] = 1,
    ACTIONS(204), 1,
      sym_text,
  [896] = 1,
    ACTIONS(206), 1,
      anon_sym_POUND_POUND_POUND_POUND,
  [900] = 1,
    ACTIONS(208), 1,
      sym_text,
  [904] = 1,
    ACTIONS(210), 1,
      sym_text,
  [908] = 1,
    ACTIONS(212), 1,
      sym_text,
  [912] = 1,
    ACTIONS(214), 1,
      anon_sym_POUND_POUND_POUND,
  [916] = 1,
    ACTIONS(216), 1,
      anon_sym_POUND_POUND_POUND,
  [920] = 1,
    ACTIONS(218), 1,
      sym_text,
  [924] = 1,
    ACTIONS(220), 1,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
  [928] = 1,
    ACTIONS(222), 1,
      anon_sym_POUND_POUND,
  [932] = 1,
    ACTIONS(224), 1,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
  [936] = 1,
    ACTIONS(226), 1,
      anon_sym_POUND_POUND_POUND_POUND,
  [940] = 1,
    ACTIONS(228), 1,
      anon_sym_POUND_POUND,
  [944] = 1,
    ACTIONS(230), 1,
      sym_text,
  [948] = 1,
    ACTIONS(232), 1,
      sym_text,
  [952] = 1,
    ACTIONS(234), 1,
      sym_text,
  [956] = 1,
    ACTIONS(236), 1,
      sym_text,
  [960] = 1,
    ACTIONS(238), 1,
      sym_text,
  [964] = 1,
    ACTIONS(240), 1,
      sym_text,
  [968] = 1,
    ACTIONS(242), 1,
      sym_text,
  [972] = 1,
    ACTIONS(244), 1,
      sym_text,
  [976] = 1,
    ACTIONS(246), 1,
      anon_sym_POUND,
  [980] = 1,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
  [984] = 1,
    ACTIONS(250), 1,
      anon_sym_POUND,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 32,
  [SMALL_STATE(9)] = 64,
  [SMALL_STATE(10)] = 96,
  [SMALL_STATE(11)] = 128,
  [SMALL_STATE(12)] = 160,
  [SMALL_STATE(13)] = 198,
  [SMALL_STATE(14)] = 224,
  [SMALL_STATE(15)] = 262,
  [SMALL_STATE(16)] = 300,
  [SMALL_STATE(17)] = 338,
  [SMALL_STATE(18)] = 376,
  [SMALL_STATE(19)] = 401,
  [SMALL_STATE(20)] = 426,
  [SMALL_STATE(21)] = 460,
  [SMALL_STATE(22)] = 494,
  [SMALL_STATE(23)] = 528,
  [SMALL_STATE(24)] = 562,
  [SMALL_STATE(25)] = 596,
  [SMALL_STATE(26)] = 617,
  [SMALL_STATE(27)] = 638,
  [SMALL_STATE(28)] = 668,
  [SMALL_STATE(29)] = 698,
  [SMALL_STATE(30)] = 728,
  [SMALL_STATE(31)] = 758,
  [SMALL_STATE(32)] = 788,
  [SMALL_STATE(33)] = 805,
  [SMALL_STATE(34)] = 822,
  [SMALL_STATE(35)] = 835,
  [SMALL_STATE(36)] = 848,
  [SMALL_STATE(37)] = 866,
  [SMALL_STATE(38)] = 884,
  [SMALL_STATE(39)] = 888,
  [SMALL_STATE(40)] = 892,
  [SMALL_STATE(41)] = 896,
  [SMALL_STATE(42)] = 900,
  [SMALL_STATE(43)] = 904,
  [SMALL_STATE(44)] = 908,
  [SMALL_STATE(45)] = 912,
  [SMALL_STATE(46)] = 916,
  [SMALL_STATE(47)] = 920,
  [SMALL_STATE(48)] = 924,
  [SMALL_STATE(49)] = 928,
  [SMALL_STATE(50)] = 932,
  [SMALL_STATE(51)] = 936,
  [SMALL_STATE(52)] = 940,
  [SMALL_STATE(53)] = 944,
  [SMALL_STATE(54)] = 948,
  [SMALL_STATE(55)] = 952,
  [SMALL_STATE(56)] = 956,
  [SMALL_STATE(57)] = 960,
  [SMALL_STATE(58)] = 964,
  [SMALL_STATE(59)] = 968,
  [SMALL_STATE(60)] = 972,
  [SMALL_STATE(61)] = 976,
  [SMALL_STATE(62)] = 980,
  [SMALL_STATE(63)] = 984,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 4),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 2),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 2),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 3),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2), SHIFT_REPEAT(38),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2), SHIFT_REPEAT(47),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2), SHIFT_REPEAT(48),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 3),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 3),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 2),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 2),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 4),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 4),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_leaf_project_repeat1, 2),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_leaf_project_repeat1, 2),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_leaf_project_repeat1, 2), SHIFT_REPEAT(58),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 4),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 4),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_comment, 2),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_comment, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_grandchild_project_repeat1, 2),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2), SHIFT_REPEAT(56),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2), SHIFT_REPEAT(39),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2), SHIFT_REPEAT(51),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 3),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 2),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 2),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_comment, 2),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_comment, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_children, 1),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_children, 1),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 3),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 3),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 2),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 4),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 4),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_child_project_repeat1, 2),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2), SHIFT_REPEAT(42),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2), SHIFT_REPEAT(40),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2), SHIFT_REPEAT(46),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_comment, 2),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_comment, 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project_great_grandchildren, 1),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project_great_grandchildren, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 3),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 3),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_root_project_repeat1, 2),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2), SHIFT_REPEAT(54),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2), SHIFT_REPEAT(53),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2), SHIFT_REPEAT(52),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 2),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 4),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 4),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project_grandchildren, 1),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project_grandchildren, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_comment, 2),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_comment, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project_children, 1),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project_children, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_comment, 2),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_comment, 2),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(59),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(63),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_collapsed_icon, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_collapsed_icon, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_collapsed_icon, 1),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_collapsed_icon, 1),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [248] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_collapsed_icon, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_projects(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
