#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 55
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_POUND = 1,
  anon_sym_POUND_POUND = 2,
  anon_sym_POUND_POUND_POUND = 3,
  anon_sym_POUND_POUND_POUND_POUND = 4,
  anon_sym_POUND_POUND_POUND_POUND_POUND = 5,
  anon_sym_PLUS = 6,
  anon_sym_PLUS_PLUS = 7,
  anon_sym_PLUS_PLUS_PLUS = 8,
  anon_sym_PLUS_PLUS_PLUS_PLUS = 9,
  anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS = 10,
  sym_text = 11,
  sym_collapsed = 12,
  sym_not_collapsed = 13,
  sym_no_children = 14,
  sym_source_file = 15,
  sym_root_project = 16,
  sym_child_project = 17,
  sym_grandchild_project = 18,
  sym_great_grandchild_project = 19,
  sym_leaf_project = 20,
  sym_project_children = 21,
  sym_project_grandchildren = 22,
  sym_project_great_grandchildren = 23,
  sym_leaf_children = 24,
  sym_root_comment = 25,
  sym_child_comment = 26,
  sym_grandchild_comment = 27,
  sym_great_grandchild_comment = 28,
  sym_leaf_comment = 29,
  sym_collapsed_icon = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_root_project_repeat1 = 32,
  aux_sym_child_project_repeat1 = 33,
  aux_sym_grandchild_project_repeat1 = 34,
  aux_sym_great_grandchild_project_repeat1 = 35,
  aux_sym_leaf_project_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [anon_sym_POUND_POUND] = "##",
  [anon_sym_POUND_POUND_POUND] = "###",
  [anon_sym_POUND_POUND_POUND_POUND] = "####",
  [anon_sym_POUND_POUND_POUND_POUND_POUND] = "#####",
  [anon_sym_PLUS] = "+",
  [anon_sym_PLUS_PLUS] = "++",
  [anon_sym_PLUS_PLUS_PLUS] = "+++",
  [anon_sym_PLUS_PLUS_PLUS_PLUS] = "++++",
  [anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS] = "+++++",
  [sym_text] = "text",
  [sym_collapsed] = "collapsed",
  [sym_not_collapsed] = "not_collapsed",
  [sym_no_children] = "no_children",
  [sym_source_file] = "source_file",
  [sym_root_project] = "root_project",
  [sym_child_project] = "child_project",
  [sym_grandchild_project] = "grandchild_project",
  [sym_great_grandchild_project] = "great_grandchild_project",
  [sym_leaf_project] = "leaf_project",
  [sym_project_children] = "project_children",
  [sym_project_grandchildren] = "project_grandchildren",
  [sym_project_great_grandchildren] = "project_great_grandchildren",
  [sym_leaf_children] = "leaf_children",
  [sym_root_comment] = "root_comment",
  [sym_child_comment] = "child_comment",
  [sym_grandchild_comment] = "grandchild_comment",
  [sym_great_grandchild_comment] = "great_grandchild_comment",
  [sym_leaf_comment] = "leaf_comment",
  [sym_collapsed_icon] = "collapsed_icon",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_root_project_repeat1] = "root_project_repeat1",
  [aux_sym_child_project_repeat1] = "child_project_repeat1",
  [aux_sym_grandchild_project_repeat1] = "grandchild_project_repeat1",
  [aux_sym_great_grandchild_project_repeat1] = "great_grandchild_project_repeat1",
  [aux_sym_leaf_project_repeat1] = "leaf_project_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_POUND_POUND] = anon_sym_POUND_POUND,
  [anon_sym_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND,
  [anon_sym_POUND_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND_POUND,
  [anon_sym_POUND_POUND_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND_POUND_POUND,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_PLUS_PLUS] = anon_sym_PLUS_PLUS,
  [anon_sym_PLUS_PLUS_PLUS] = anon_sym_PLUS_PLUS_PLUS,
  [anon_sym_PLUS_PLUS_PLUS_PLUS] = anon_sym_PLUS_PLUS_PLUS_PLUS,
  [anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS] = anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
  [sym_text] = sym_text,
  [sym_collapsed] = sym_collapsed,
  [sym_not_collapsed] = sym_not_collapsed,
  [sym_no_children] = sym_no_children,
  [sym_source_file] = sym_source_file,
  [sym_root_project] = sym_root_project,
  [sym_child_project] = sym_child_project,
  [sym_grandchild_project] = sym_grandchild_project,
  [sym_great_grandchild_project] = sym_great_grandchild_project,
  [sym_leaf_project] = sym_leaf_project,
  [sym_project_children] = sym_project_children,
  [sym_project_grandchildren] = sym_project_grandchildren,
  [sym_project_great_grandchildren] = sym_project_great_grandchildren,
  [sym_leaf_children] = sym_leaf_children,
  [sym_root_comment] = sym_root_comment,
  [sym_child_comment] = sym_child_comment,
  [sym_grandchild_comment] = sym_grandchild_comment,
  [sym_great_grandchild_comment] = sym_great_grandchild_comment,
  [sym_leaf_comment] = sym_leaf_comment,
  [sym_collapsed_icon] = sym_collapsed_icon,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_root_project_repeat1] = aux_sym_root_project_repeat1,
  [aux_sym_child_project_repeat1] = aux_sym_child_project_repeat1,
  [aux_sym_grandchild_project_repeat1] = aux_sym_grandchild_project_repeat1,
  [aux_sym_great_grandchild_project_repeat1] = aux_sym_great_grandchild_project_repeat1,
  [aux_sym_leaf_project_repeat1] = aux_sym_leaf_project_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_collapsed] = {
    .visible = true,
    .named = true,
  },
  [sym_not_collapsed] = {
    .visible = true,
    .named = true,
  },
  [sym_no_children] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_root_project] = {
    .visible = true,
    .named = true,
  },
  [sym_child_project] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_project] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_project] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_project] = {
    .visible = true,
    .named = true,
  },
  [sym_project_children] = {
    .visible = true,
    .named = true,
  },
  [sym_project_grandchildren] = {
    .visible = true,
    .named = true,
  },
  [sym_project_great_grandchildren] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_children] = {
    .visible = true,
    .named = true,
  },
  [sym_root_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_child_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_grandchild_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_great_grandchild_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_collapsed_icon] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_child_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_grandchild_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_great_grandchild_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_leaf_project_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '+') ADVANCE(11);
      if (lookahead == '>') ADVANCE(1);
      if (lookahead == 'v') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '>') ADVANCE(1);
      if (lookahead == 'v') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') SKIP(4)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(7);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      if (lookahead == '#') ADVANCE(8);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      if (lookahead == '#') ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND_POUND);
      if (lookahead == '#') ADVANCE(10);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND_POUND_POUND);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '+') ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS);
      if (lookahead == '+') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS_PLUS);
      if (lookahead == '+') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS_PLUS_PLUS);
      if (lookahead == '+') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_collapsed);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_not_collapsed);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_not_collapsed);
      if (lookahead == ' ' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_no_children);
      if (lookahead == ' ') ADVANCE(22);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS] = ACTIONS(1),
    [sym_collapsed] = ACTIONS(1),
    [sym_not_collapsed] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(54),
    [sym_root_project] = STATE(42),
    [aux_sym_source_file_repeat1] = STATE(42),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    ACTIONS(13), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    STATE(6), 2,
      sym_leaf_children,
      aux_sym_great_grandchild_project_repeat1,
    STATE(19), 2,
      sym_leaf_project,
      sym_great_grandchild_comment,
    ACTIONS(9), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
  [27] = 6,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    ACTIONS(13), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    STATE(5), 2,
      sym_leaf_children,
      aux_sym_great_grandchild_project_repeat1,
    STATE(19), 2,
      sym_leaf_project,
      sym_great_grandchild_comment,
    ACTIONS(9), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
  [54] = 6,
    ACTIONS(11), 1,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    ACTIONS(13), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(2), 2,
      sym_leaf_children,
      aux_sym_great_grandchild_project_repeat1,
    STATE(19), 2,
      sym_leaf_project,
      sym_great_grandchild_comment,
    ACTIONS(17), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
  [81] = 6,
    ACTIONS(11), 1,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    ACTIONS(13), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(6), 2,
      sym_leaf_children,
      aux_sym_great_grandchild_project_repeat1,
    STATE(19), 2,
      sym_leaf_project,
      sym_great_grandchild_comment,
    ACTIONS(21), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
  [108] = 6,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    ACTIONS(30), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    STATE(6), 2,
      sym_leaf_children,
      aux_sym_great_grandchild_project_repeat1,
    STATE(19), 2,
      sym_leaf_project,
      sym_great_grandchild_comment,
    ACTIONS(25), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
  [135] = 4,
    ACTIONS(37), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    STATE(8), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(35), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
  [157] = 4,
    ACTIONS(43), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    STATE(8), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(41), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
  [179] = 4,
    ACTIONS(37), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    STATE(8), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(48), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
  [201] = 4,
    ACTIONS(37), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    STATE(7), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(48), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
  [223] = 4,
    ACTIONS(37), 1,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
    STATE(9), 2,
      sym_leaf_comment,
      aux_sym_leaf_project_repeat1,
    ACTIONS(52), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
  [245] = 6,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(60), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(15), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(31), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(56), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
  [270] = 6,
    ACTIONS(58), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(60), 1,
      anon_sym_PLUS_PLUS_PLUS,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    STATE(14), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(31), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(64), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
  [295] = 6,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(73), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(14), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(31), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(68), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
  [320] = 6,
    ACTIONS(58), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(60), 1,
      anon_sym_PLUS_PLUS_PLUS,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    STATE(14), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(31), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(78), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
  [345] = 6,
    ACTIONS(58), 1,
      anon_sym_POUND_POUND_POUND_POUND,
    ACTIONS(60), 1,
      anon_sym_PLUS_PLUS_PLUS,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    STATE(13), 2,
      sym_project_great_grandchildren,
      aux_sym_grandchild_project_repeat1,
    STATE(31), 2,
      sym_great_grandchild_project,
      sym_grandchild_comment,
    ACTIONS(78), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
  [370] = 2,
    ACTIONS(80), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(82), 8,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
  [386] = 6,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(90), 1,
      anon_sym_PLUS_PLUS,
    STATE(20), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(33), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(86), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [409] = 2,
    ACTIONS(92), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(94), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
  [424] = 6,
    ACTIONS(88), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(90), 1,
      anon_sym_PLUS_PLUS,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    STATE(23), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(33), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(98), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [447] = 6,
    ACTIONS(88), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(90), 1,
      anon_sym_PLUS_PLUS,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    STATE(24), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(33), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(98), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [470] = 2,
    ACTIONS(100), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
    ACTIONS(102), 7,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_PLUS_PLUS_PLUS,
  [485] = 6,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(108), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(111), 1,
      anon_sym_PLUS_PLUS,
    STATE(23), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(33), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(106), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [508] = 6,
    ACTIONS(88), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(90), 1,
      anon_sym_PLUS_PLUS,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    STATE(23), 2,
      sym_project_grandchildren,
      aux_sym_child_project_repeat1,
    STATE(33), 2,
      sym_grandchild_project,
      sym_child_comment,
    ACTIONS(116), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [531] = 6,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 1,
      anon_sym_POUND,
    ACTIONS(122), 1,
      anon_sym_POUND_POUND,
    ACTIONS(124), 1,
      anon_sym_PLUS,
    STATE(30), 2,
      sym_project_children,
      aux_sym_root_project_repeat1,
    STATE(40), 2,
      sym_child_project,
      sym_root_comment,
  [552] = 6,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 1,
      anon_sym_POUND,
    ACTIONS(122), 1,
      anon_sym_POUND_POUND,
    ACTIONS(124), 1,
      anon_sym_PLUS,
    STATE(27), 2,
      sym_project_children,
      aux_sym_root_project_repeat1,
    STATE(40), 2,
      sym_child_project,
      sym_root_comment,
  [573] = 6,
    ACTIONS(122), 1,
      anon_sym_POUND_POUND,
    ACTIONS(124), 1,
      anon_sym_PLUS,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    ACTIONS(128), 1,
      anon_sym_POUND,
    STATE(30), 2,
      sym_project_children,
      aux_sym_root_project_repeat1,
    STATE(40), 2,
      sym_child_project,
      sym_root_comment,
  [594] = 6,
    ACTIONS(122), 1,
      anon_sym_POUND_POUND,
    ACTIONS(124), 1,
      anon_sym_PLUS,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 1,
      anon_sym_POUND,
    STATE(25), 2,
      sym_project_children,
      aux_sym_root_project_repeat1,
    STATE(40), 2,
      sym_child_project,
      sym_root_comment,
  [615] = 2,
    ACTIONS(134), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS,
    ACTIONS(136), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
  [628] = 6,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 1,
      anon_sym_POUND,
    ACTIONS(142), 1,
      anon_sym_POUND_POUND,
    ACTIONS(145), 1,
      anon_sym_PLUS,
    STATE(30), 2,
      sym_project_children,
      aux_sym_root_project_repeat1,
    STATE(40), 2,
      sym_child_project,
      sym_root_comment,
  [649] = 2,
    ACTIONS(148), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS_PLUS,
    ACTIONS(150), 5,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
  [662] = 2,
    ACTIONS(152), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS,
    ACTIONS(154), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [673] = 2,
    ACTIONS(156), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
      anon_sym_PLUS_PLUS,
    ACTIONS(158), 3,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [684] = 3,
    ACTIONS(160), 1,
      sym_text,
    STATE(48), 1,
      sym_collapsed_icon,
    ACTIONS(162), 3,
      sym_collapsed,
      sym_not_collapsed,
      sym_no_children,
  [696] = 3,
    ACTIONS(164), 1,
      sym_text,
    STATE(52), 1,
      sym_collapsed_icon,
    ACTIONS(162), 3,
      sym_collapsed,
      sym_not_collapsed,
      sym_no_children,
  [708] = 3,
    ACTIONS(166), 1,
      sym_text,
    STATE(49), 1,
      sym_collapsed_icon,
    ACTIONS(162), 3,
      sym_collapsed,
      sym_not_collapsed,
      sym_no_children,
  [720] = 3,
    ACTIONS(168), 1,
      sym_text,
    STATE(44), 1,
      sym_collapsed_icon,
    ACTIONS(162), 3,
      sym_collapsed,
      sym_not_collapsed,
      sym_no_children,
  [732] = 3,
    ACTIONS(170), 1,
      sym_text,
    STATE(43), 1,
      sym_collapsed_icon,
    ACTIONS(162), 3,
      sym_collapsed,
      sym_not_collapsed,
      sym_no_children,
  [744] = 2,
    ACTIONS(174), 1,
      anon_sym_POUND,
    ACTIONS(172), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [753] = 2,
    ACTIONS(178), 1,
      anon_sym_POUND,
    ACTIONS(176), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND,
      anon_sym_PLUS,
  [762] = 3,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 1,
      anon_sym_POUND,
    STATE(41), 2,
      sym_root_project,
      aux_sym_source_file_repeat1,
  [773] = 3,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
    STATE(41), 2,
      sym_root_project,
      aux_sym_source_file_repeat1,
  [784] = 1,
    ACTIONS(187), 1,
      sym_text,
  [788] = 1,
    ACTIONS(189), 1,
      sym_text,
  [792] = 1,
    ACTIONS(191), 1,
      sym_text,
  [796] = 1,
    ACTIONS(193), 1,
      sym_text,
  [800] = 1,
    ACTIONS(195), 1,
      sym_text,
  [804] = 1,
    ACTIONS(197), 1,
      sym_text,
  [808] = 1,
    ACTIONS(199), 1,
      sym_text,
  [812] = 1,
    ACTIONS(201), 1,
      sym_text,
  [816] = 1,
    ACTIONS(203), 1,
      sym_text,
  [820] = 1,
    ACTIONS(205), 1,
      sym_text,
  [824] = 1,
    ACTIONS(207), 1,
      sym_text,
  [828] = 1,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 81,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 135,
  [SMALL_STATE(8)] = 157,
  [SMALL_STATE(9)] = 179,
  [SMALL_STATE(10)] = 201,
  [SMALL_STATE(11)] = 223,
  [SMALL_STATE(12)] = 245,
  [SMALL_STATE(13)] = 270,
  [SMALL_STATE(14)] = 295,
  [SMALL_STATE(15)] = 320,
  [SMALL_STATE(16)] = 345,
  [SMALL_STATE(17)] = 370,
  [SMALL_STATE(18)] = 386,
  [SMALL_STATE(19)] = 409,
  [SMALL_STATE(20)] = 424,
  [SMALL_STATE(21)] = 447,
  [SMALL_STATE(22)] = 470,
  [SMALL_STATE(23)] = 485,
  [SMALL_STATE(24)] = 508,
  [SMALL_STATE(25)] = 531,
  [SMALL_STATE(26)] = 552,
  [SMALL_STATE(27)] = 573,
  [SMALL_STATE(28)] = 594,
  [SMALL_STATE(29)] = 615,
  [SMALL_STATE(30)] = 628,
  [SMALL_STATE(31)] = 649,
  [SMALL_STATE(32)] = 662,
  [SMALL_STATE(33)] = 673,
  [SMALL_STATE(34)] = 684,
  [SMALL_STATE(35)] = 696,
  [SMALL_STATE(36)] = 708,
  [SMALL_STATE(37)] = 720,
  [SMALL_STATE(38)] = 732,
  [SMALL_STATE(39)] = 744,
  [SMALL_STATE(40)] = 753,
  [SMALL_STATE(41)] = 762,
  [SMALL_STATE(42)] = 773,
  [SMALL_STATE(43)] = 784,
  [SMALL_STATE(44)] = 788,
  [SMALL_STATE(45)] = 792,
  [SMALL_STATE(46)] = 796,
  [SMALL_STATE(47)] = 800,
  [SMALL_STATE(48)] = 804,
  [SMALL_STATE(49)] = 808,
  [SMALL_STATE(50)] = 812,
  [SMALL_STATE(51)] = 816,
  [SMALL_STATE(52)] = 820,
  [SMALL_STATE(53)] = 824,
  [SMALL_STATE(54)] = 828,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 3),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 2),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_project, 4),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_project, 4),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2), SHIFT_REPEAT(36),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_great_grandchild_project_repeat1, 2), SHIFT_REPEAT(46),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 4),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 4),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_leaf_project_repeat1, 2),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_leaf_project_repeat1, 2),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_leaf_project_repeat1, 2), SHIFT_REPEAT(51),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 3),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 3),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_project, 2),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_project, 2),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 2),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 2),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 4),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 4),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_grandchild_project_repeat1, 2),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2), SHIFT_REPEAT(38),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grandchild_project_repeat1, 2), SHIFT_REPEAT(45),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_project, 3),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_project, 3),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_comment, 2),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_comment, 2),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 2),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 2),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_children, 1),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leaf_children, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 3),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 3),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_great_grandchild_comment, 2),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_great_grandchild_comment, 2),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_child_project_repeat1, 2),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2), SHIFT_REPEAT(37),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_child_project_repeat1, 2), SHIFT_REPEAT(47),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_project, 4),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_project, 4),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 3),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 4),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 4),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_project, 2),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_project, 2),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grandchild_comment, 2),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grandchild_comment, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_root_project_repeat1, 2),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2), SHIFT_REPEAT(34),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_project_repeat1, 2), SHIFT_REPEAT(50),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project_great_grandchildren, 1),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project_great_grandchildren, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_comment, 2),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child_comment, 2),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project_grandchildren, 1),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project_grandchildren, 1),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_comment, 2),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_comment, 2),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project_children, 1),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project_children, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(35),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_collapsed_icon, 1),
  [209] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_projects(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
